### ISSUE TITLE
Add is_proband field to Association Table Participant-Study

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#108]
Add a boolean field that denotes whether or not the Participant is a proband.
Add this field to the association table between Participant and Study tables

**Comment by znatty22** [comment]
Was thinking about this more and I'm not sure its a good idea to have the `is_proband` field on Participant model. What if a participant is involved in two studies where they are the proband in one study but not the other? 

This could be accounted for in two ways: the participant would have 2 rows in the Participant table,  where the `external_id` field would be the same for both rows (denoting that this is the same participant) but `is_proband` would be different. This works, but is not ideal for obvious reasons.

@dankolbman suggested that since there is a many-to-many relationship between Participant and Study, why not put the `is_proband` field on the association table between Participant and Study?

@allisonheath what do you think?

**Comment by allisonheath** [comment]
@znatty22 I think that makes sense, also looks like how @junjun-zhang had positioned it in the ES mapping

**Comment by znatty22** [comment]
OBE, this field is moving to Participant model. See #106
