### ISSUE TITLE
relationships among entities on ER diagram are wrong

### ISSUE THREAD

**Issue by grant-guo** [kids-first/kf-api-dataservice#110]
for example, "participant" and "diagnosis", the label on the "participant" side should be {0,1}, which means a diagnosis belongs to one participant. Also, the label on the "diagnosis" side should be {0, N}, which means one participant could have zero or more diagnosis

At the same time, I question 0 in multiplicity. If a diagnosis exists, it should belong to a participant. "0" here doesn't make sense

**Comment by parimalak** [comment]
we have seen this as well, see #94

**Comment by allisonheath** [comment]
Duplicate of #94

**Comment by allisonheath** [comment]
p.s. nice to see you're looking @grant-guo 😂 maybe add the multiplicity note to the other ticket so we can see if we can address both at the same time?
