### ISSUE TITLE
Add new fields to diagnosis entity

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#116]
1.Add diagnosis_category 
Will contain very high level categorization like `cancer` and `birth defect`.
2.Add tumor_location 
This field is for cancers and we should try to harmonize to the locations for GDC's primary site: https://github.com/NCI-GDC/gdcdictionary/blob/develop/gdcdictionary/schemas/case.yaml#L183-L277 (this is also the high level values for ICD-0 Topology: http://codes.iarc.fr/topography)

**Comment by parimalak** [comment]
#113
