### ISSUE TITLE
Add pagination to participant resource

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-dataservice#12]
The top level resources that return lists should return items in a paginated format using a configurable number of results.

This should be implemented using good practices for pagination against the database such as use of a cursor.

Information about the page number, total number of results, etc. should also be returned either through the header or in a standardized envelope.

Examples:

```
GET /persons

{
  "_links": {
    "prev": "/persons?page=1",
    "self": "/persons?page=2",
    "next": "/persons?page=3"
  },
  "total": 23,
  "limit": 10,
  "results": {
    {"kf_id": "001"},
    {"kf_id": "002"},
    ...
    {"kf_id": "010"}
  }
}
```

**Comment by baileyckelly** [comment]
This issue will complete the review for the main pagination code. There will be a separate issue to update all resources with the 1 or 2 line change for adding pagination.
