### ISSUE TITLE
Change IDs

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#127]
Per conversations in the design meeting this morning, it was discussed to change the ID prefixes

**Comment by dankolbman** [comment]
The 8-char crockford encoding is pretty nice for the unique bit, we also seem happy about two char prefixes, question is if there should be some sort of delimeter.
Examples:
`PT9J23ZYNA` - for participant
`PT-9J23ZYNA`
`PT:9J23ZYNA`
`PT.9J23ZYNA`

**Comment by junjun-zhang** [comment]
I think having delimiter is nice.  Without it, it could be hard to see what is the prefix, eg: `PTTTP234GX`. 

In terms of what's a good choice for delimiter, I personally like underscore `_`, eg: `PT_TTP234GX`. It is used in GenBank's RefSeq accessions: https://support.ncbi.nlm.nih.gov/link/portal/28045/28049/Article/502/

Also, not really matter, but `_` is usually allowed character as part of variable name in many programming languages, while `.`, `-` etc are not.

**Comment by dankolbman** [comment]
Underscore came up in our discussions. We were concerned that it's not officially allowed as a character in urls, but it turns out it's only invalid in hostnames.

**Comment by allisonheath** [comment]
Ok great - my vote is then `_` as well

**Comment by junjun-zhang** [comment]
Interestingly, I found this: http://compbio.charite.de/hpoweb/showterm?id=HP:0000504, note that the PRUL for this HPO term is: http://purl.obolibrary.org/obo/HP_0000504. Underscore is definitely more URL-friendly than colon `:` which will be encoded as `%3A`, while `_` remains unchanged.

**Comment by dankolbman** [comment]
Ok, going with `_`!
