### ISSUE TITLE
Change self link format or implement query parameters

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#172]
Currently all of the self links are endpoints which have `kf_id` as a query parameter like so: 
```
"self": "/participants?kf_id=PT_7MJ05MNZ"
```
The dataservice does not currently support query parameters except for pagination. This means none of the self links will retrieve the expected resource. In the example above, that endpoint will not retrieve participant PT_7MJ05MNZ. Instead the result will be the default, which is the first page of participants.

To solve this, we have a couple options: 

1) Change self links to this format: 
```
"self": "/participants/PT_7MJ05MNZ"
```
or 2) Keep the self links the way they are and implement query parameters

**Comment by dankolbman** [comment]
This is a bug and prevents navigation using the `self` link.

We should go with the first option (reformatting) and then consider further filter paramaters as part of issue #104
