### ISSUE TITLE
Model Updates

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#185]
1. Add `is_harmonized` field to GenomicFile?
2. Add `status` or `release_status` to Study?
3. Should Aliquot `concentration` be a float? Currently it is an integer
4. Should fields which represent measured quantities (i.e. concentration, volume, etc) have additional fields on the model to store units?

**Comment by znatty22** [comment]
@allisonheath thoughts?

**Comment by allisonheath** [comment]
1. Yes
2. Let's make it `release_status` to Study
3. Yes, `concentration` and `volume` should be floats. 
4. We can either add a units column or just say they have to be a certain unit for now and add to the field name, like how we have `age_at_event_days`.

Two other fields to add: `mondo` for diagnosis and `uberon` in sample (for anatomical site).

**Comment by parimalak** [comment]
For 4, see https://github.com/kids-first/kf-api-dataservice/blob/master/dataservice/api/aliquot/models.py . Units for concentration is mg/ml and for volume is ml.

**Comment by allisonheath** [comment]
We should also add `NCIt` in diagnosis as well for the moment, although it is on the roadmap for this to get integrated into MONDO.

**Comment by znatty22** [comment]
Summary of changes in this issue:
- [ ] Add `release_status` field to study
- [ ] Add `icd_id`, `mondo_id` fields to diagnosis
- [ ] Add `snowmed_id` field to phenotype
- [ ] Add `is_harmonized`, `original_reference_genome` fields to genomic_file 

These changes will be in incorporated in #202:
- [ ] Update `concentration` field to Float for aliquot model
- [ ] Add `uberon_id` field to sample
