### ISSUE TITLE
Create list of DevOPS questions for OICR

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#19]
Create a list of DevOps questions to get AWS ready for dev deployment. We would like to bring this to the Wednesday tech meetings.

**Comment by baileyckelly** [comment]
@alubneuski @dankolbman Sent you teh google doc for questions

**Comment by allisonheath** [comment]
Should we move this to the internal devops tracker instead of dataservice?

**Comment by dankolbman** [comment]
Yes please :pray:

**Comment by allisonheath** [comment]
Issue moved to [kids-first/kf-devops-internal-tracker #16](https://github.com/kids-first/kf-devops-internal-tracker/issues/16) via [**ZenHub**](https://www.zenhub.com/)
