### ISSUE TITLE
Add 400+ Responses to kf-dataservice Documentation

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#192]
Currently our API docs have example 200 responses included for each endpoint. We should add example 400/404 responses to each of the endpoints.

**Comment by dankolbman** [comment]
Should be pretty easy to define new [templates](https://github.com/kids-first/kf-api-dataservice/tree/master/dataservice/api/templates) for each of the errors.
The templates use jinja so you can easily extend the base responses that are there now with other external files.
