### ISSUE TITLE
Create initial Study model

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#22]
The externally existing concept is one of a ["dbGaP Study"](https://www.ncbi.nlm.nih.gov/books/NBK154410/). In dbGaP two major use cases for the study are:

1. Access control, once you're approved for access you have access to *all* data in the study
2. Consent groups for DUL and reviewing of access requests

The second use case is typically not discussed outside of dbGaP but is an important component for Kids First. In reality, consent is tied to a specific study protocol as determined by an IRB. So someone can participate in multiple different studies resulting in physical samples, genomic data, clinical data, etc. that are covered under the consent of one or more of studies they participated in. 

Separately in portal design discussions we had developed the concept of `Dataset` being 
"a set of data created by a particular entity tied to access, data use limitations, IRB/institutions (specific X01 cohorts (dbGaP))". 

So we need to resolve the above into what we're going to track in our data model. The immediate use cases I see are:
- Tracking what dbGaP study each file (or perhaps entity as well) belongs to for authorized access
- Tracking a participants consent tied to a specific IRB study protocol and which of the entities related to that participant are covered under that consent, especially if a participant is under more than one dbGaP study

There are some foreseeable use cases if we want to bring datasets that aren't managed under the purview of dbGaP. This would include designating "data ownership" and the ability for that data owner to grant access (this is really how I think we should think about dbGaP, it just happens in an automated way from our point of view). For example, including consortium-based or foundation based datasets. This is longer term, but perhaps important to consider so we don't get backed into only supporting the dbGaP use cases.

**Comment by allisonheath** [comment]
Per conversation today, for the MVP we'll go with `study` which will be analogous to a dbGaP study. Fields to be for MVP:

`data_access_authority`: `dbGaP`
`external_id`: dbGaP accession number, e.g. `phs000178`
`version`: the dbgap version e.g. `v9.p8`
`name`: the name/title
`attribution`: link to attribution prose provided by dbgap, e.g. https://dbgap.ncbi.nlm.nih.gov/aa/wga.cgi?view_pdf&stacc=phs000178.v9.p8

~While in general, study can be many to many to both participant and sample. I expect for most of the initial dbGaP studies they'll be one to many~.  

For MVP:
`Study` can be many to many to `Participant`
`Study` will only be one to many to `Sample`, the downstream `GenomicFiles` will therefore belong to the study from the sample and access control will be managed that way
If it becomes necessary for MVP to support other file types, they will be linked back to just one study.

For post-MVP, we need to more fully flesh out the use cases. From the initial write up, I could imagine introducing a secondary concept (e.g. dataset) that more directly controls access versus the MVP setup where the study information about consent/research goals indirectly controls access in this manner.

**Comment by dankolbman** [comment]
This seems pretty good for the assumption we'll be working with only dbGaP stuff for a while.

Some nits:
We may want to store the phs id as the `external_id` or something other than `study_id` as we'll probably want to use a kf_id as the primary id throughout, and `study_id` may be misleading.
We also could do without prefixing the other fields with `study_` as it should be implied.

**Comment by znatty22** [comment]
@allisonheath Can participants exist without being linked to a study? Right now my assumption is that a participant must be linked to a study.

Something to consider ...
If a participant must be linked to a study then when a study is deleted, all of it's participants will be deleted.

**Comment by allisonheath** [comment]
@znatty22 I think that's correct, participants have to be linked to study. And it makes sense that they'd be deleted if a study is deleted. And that would be mean everything downstream from the participant (sample, diagnoses, etc.) would all be deleted as well (and I think that would be the correct behavior).
