### ISSUE TITLE
Sequencing Center Model and Endpoints

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#220]

**Comment by dankolbman** [comment]
The sequencer model is currently captured in sequencing experiment. Does it make sense to have it on the Sequencing Center?

**Comment by parimalak** [comment]
@dankolbman I think we agreed to have separate center table and we renamed as `SequencingCenter`

**Comment by dankolbman** [comment]
Hah, I see why I was confused about this. I thought this was in reference to adding a field for sequencer model to the Sequencing Center table...
