### ISSUE TITLE
Question about data for the data tracker

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-dataservice#224]
from @HuangXiaoyan0106 

I want to get the information from database as follows:
-  Have the samples been received?
-  Have the samples been sequenced?
-  Have received the sequenced data?
-  Have got the clinical/phenotype data?
-  Have got the genomic data?
-  Have got the harmonized genomic data?
 
Form the layout of the database, I got those information as follows:
- The characters in “aliquot” may be used to speculate the status of “sample received”. But the “shipment_date” is null. When considering the “volume”, I found the same sample id with none volume but have genomic file in “sequencing_experiment”. So, I have some confusion about this.
- I speculate the “sample sequenced” and “sequenced data received” status according to the “genomic_file” in “sequencing_experiment”.
- For “clinical/phenotype data”, I got it from “diagnosis”. But there are also “phenotype” item in the database, I want to know the difference between them.
- For “genomic data” and “harmonized genomic data”, I don’t know where to fetch them.
 
 
- What’s more, I traced the institution name based on the sample id but found that some samples could not find the “name/institution” in “investigator”.
-  Lastly, I want to know in which year that samples were recruited into kid-first project. But I just found the “created_at” item in “Sample”. I don’t know where to get this information.

**Comment by dankolbman** [comment]
Some of these questions are still open on our end, so we may not be able to answer them confidently at the moment.

Regarding the info you're looking for:

- Have the samples been received?

It's not sure whether we'll be able to provide this information accurately. Although we could make strict requirements around submitting of manifests and following the full lifetime of the sample, we will likely only worry about the samples once the genomic data comes to us.

We don't always receive any information about the volume, so you will often find null values

- Have the samples been sequenced?

This is likely when we will be made aware of a sample, so it would be safe to assume any biospecimen with a `genomic_file` of a reads has been sequenced.

- Have received the sequenced data?

Same as above. We probably won't have the resolution to differentiate between `have been sequenced` and `sequenced data received`

- Have got the clinical/phenotype data?

Likely safe to assume that if the biospecimen is related to a participant, then we have the clinical data. Clinical data usually consists of a diagnosis, and a number of observed phenotypes in that participant.

- Have got the genomic data?

Know by the presence of genomic_files on a biospecimen

- Have got the harmonized genomic data?

The harmonized genomic data will be `genomic_file`s similar to the raw data, but will be outputs of a workflow.

the `created_at` time is essentially when that entity was submitted to the kid's first project..

**Comment by allisonheath** [comment]
Agree - these questions are open, but are ones we should try to come to consensus on the answers to, and we have some ability to help provide recommendations moving forward. However, currently the typical mode of operation gives us three major events for a cohort: 
1) samples are shipped 
2) clinical data is provided on participant 
3) sequencing data is received

The plan is for us to get the shipping manifest of the samples when they are shipped from the collection site to the sequencing center. So at that point we should be aware of the samples and should be able to populate those entities/fields. Moving forward, we're looking at putting together recommended fields to capture so we can get things like volume better populated, but retrospectively we're working with what we have - similarly to shipment data.

Typically, we don't get any information about the samples being received by the center, unless something goes wrong. Thinking about that, we should consider adding a field to capture if the sample wasn't sequenced for one reason or another to indicate we aren't expecting any genomic data back. Reasons this can happen include the sample not passing initial QC in prep, not passing QC after sequencing, or the sample is destroyed (e.g. things like being dropped). 

During the time period when samples have been shipped is usually when we've seen the research groups work on compiling and providing the clinical data, as that is the criteria for data release. Then, once sequencing data is received and clinical data validated the sequencing data is released.

I think for "year samples were recruited" - is this for the concept of FY15 vs FY16 vs FY17. I think there was some thought in rethinking these categories overall so we should discuss what that might look like.
