### ISSUE TITLE
Add ncit_id to Diagnosis and Biospecimen

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#231]
Add `ncit_id` field to models to capture cancer terms

**Comment by dankolbman** [comment]
Which entities to include this on is TBD

**Comment by allisonheath** [comment]
Diagnosis for sure (coding of the `source_text_diagnosis`).

I think in biospecimen one for `tissue_type` and one for `tumor_descriptor`.

Phenotype as well (coding of the `source_text_phenotype`). Might ultimately be duplicative with HPO, but let's do it upfront and then revisit when we have real data to analyze.

**Comment by allisonheath** [comment]
Per @cmungall: "in general HPO will give higher precision for most phenotypes, but NCIT will
give higher precision for neoplasms". So the recommendation for phenotype is just to take HPO, I think in general this fits with the fact that often the cancer cohorts use NCIt for cancer-related terms, but either aren't collecting phenotypes or not using a specific standard. So let's leave it off of phenotype for now with the target to standardize to HPO.

The other entities still get NCIt as they are often related to the neoplasm.
