### ISSUE TITLE
Add spatial descriptor alongside anatomical entities

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-dataservice#232]
May need to break into another AnatomicalPhenotype to capture this information.

**Comment by allisonheath** [comment]
As a bit of background, in general Uberon tries to avoid pre-composing left and right forms where these are symmetric and recommended tracking separately. So while there is left/right brain there isn't left/right femur. However, tracking the sidedness can be important in understanding anatomical progression of a cancer. For example, if a tumor originates in the left tibia, having it progress to the left femur can be a different indication versus progressing to the right femur. So we'd like to track it when it's not possible to indicate using the ontology.

**Comment by allisonheath** [comment]
So after some discussions with @taylordm and @mellybelly I think we should:
- Call this field `spatial_descriptor`
- Populate it with BSPO terms, most common right now are likely `left side` and `right side` from https://www.ebi.ac.uk/ols/ontologies/bspo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBSPO_0000054 but this should cover more use cases that might arise in the future

**Comment by parimalak** [comment]
@allison `spatial_descriptor` should be added in `diagnosis`(`source_text_tumor_location`) and in `biospecimen`(`source_text_anatomical_site`) ?

**Comment by allisonheath** [comment]
@parimalak yes, everywhere there's a location on the body should have the ability to get mapped to both Uberon and BSPO

**Comment by parimalak** [comment]
👍
