### ISSUE TITLE
Update KF Dataservice ETL to reflect model changes, meeting feedback, etc

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#239]
- [x] Merge Participant + demographic - update mappings + extract modules (all studies)
- [x] Merge sample + aliquot into biospecimen - update mappings + extract modules (all studies)
- [x] Link sequencing experiment directly to genomic_file (all studies)
- [x] Populate Diagnosis.diagnosis_category with either: Structural Birth Defect or Cancer (all studies)
- [x] Update genomic_file mapping based on GenomicFile model changes from #145 (all studies)
- [x] Update participant mapping + extract modules to use Family model (all studies)
- [ ] Update phenotype/diagnosis based on affected field in the raw data (Chung study)
- [x] Update genomic_file mapping + extract modules to use SequencingCenter model (all studies)
- [x] Update study_file mapping + extract modules to use new indexd study-file model (all studies)
- [x] Update all mappings with model changes from #242

**Comment by dankolbman** [comment]
Also need to rewrite etl to use rest api. We should discuss how to organize this during planning.

**Comment by parimalak** [comment]
Yeah, also having separate repo or merging the data import to data service would be good. So, we can periodically updates whenever we change model.
