### ISSUE TITLE
Implement/Verify all resource links

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#245]
Verify that the `_links` element in any dataservice response has the correct related entity links. Every entity that has a parent should have a link to it's parent in `_links`. If a link isn't there implement it.

This is especially important for genomic file since Cavatica task service wants to collect all the clinical data for a particular genomic file. In order to do this, the service will need to follow the links back to the participant and collect the response data as it traverses.

**Comment by parimalak** [comment]
we have missing sequencing_experiment and genomic_files
