### ISSUE TITLE
Short names for studies

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#246]
To help facilitate searching and display, we should provide a short name for studies. Ideally this would be provided by the study, but we may have to retrospectively come up with some of them. There should be a length constraint of up to 26 characters.

**Comment by dankolbman** [comment]
We will come up with candidate short names and check back with X01s before making them official.
Tracking of the names is happening on the[ Dataset Prioritization](https://kidsfirst.atlassian.net/wiki/spaces/KFDRC/pages/462553261/Dataset+Prioritization) wiki page
