### ISSUE TITLE
Create initial GenomicFile Entity

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#25]
*User Story*
As a Kids First developer, I would like basic CRUD functionality to work with a File.

*Tasks*
- [ ] Create Model
- [ ] Resource
- [ ] API: Put, Patch, Delete, Get

*Acceptance Criteria*
Documentation
Have Put, Patch, Delete, Get
Unit Tests - Tests on Model, Resource, API

**Comment by allisonheath** [comment]
Fields:
`vital_status`: Alive, Dead, Not Reported
`disease_related`: true if Dead and cause of death was disease related, false if Dead and cause of death was disease related, Not Reported
