### ISSUE TITLE
correct the errors in API documents

### ISSUE THREAD

**Issue by grant-guo** [kids-first/kf-api-dataservice#254]
1. "next" and "self" fields in the response refer to "/participants?after=..."

2. the response of `study-files` endpoint is wrong, so far seems copied from `studies` endpoint

**Comment by znatty22** [comment]
The PR for issue #192 includes a fix for this

**Comment by dankolbman** [comment]
@znatty22 looks like the study-files was a bug in the study file resource. Put in pr #255
