### ISSUE TITLE
missing format setting for date fields: experiment_date and shipment_date

### ISSUE THREAD

**Issue by junjun-zhang** [kids-first/kf-api-dataservice#265]
They are currently set as ordinary `string`, will need to add `"format": "date-time"`

**Comment by dankolbman** [comment]
The fields being referenced here are from the models in the `/swagger.json` endpoint that define the swagger schema.
The `created_at` and `modified_at` fields seem to be properly formatted, so should be able to figure out what's going wrong by comparing those.
