### ISSUE TITLE
Discuss SequencingExperiment wrt to GenomicFile

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#278]
Today we discussed whether it makes sense for ALL genomic files to have a mandatory sequencing experiment. Makes sense for the input/unharmonized genomic files but not for the harmonized genomic files. We think that the foreign key to sequencing experiment inside the genomic file model should be nullable to support this case.

This will also simplify the lambda for ingesting harmonized genomic files since they will only need to be linked to biospecimens before ingestion.

**Comment by allisonheath** [comment]
I agree that it doesn't make sense for harmonized data, so if we're keeping all of them in the same table then it needs to be nullable. 

Do they have to link to another genomic file in that case?

**Comment by parimalak** [comment]
@allisonheath i think `workflow_genomic_file` model links the all the harmonized genomic_files

**Comment by allisonheath** [comment]
I was just thinking if it's possible to have an "orphaned" `genomic_file` that doesn't link back to a study, one where both the sequencing center is null and it doesn't link back to a genomic_file?

**Comment by parimalak** [comment]
in this case `sequencing_center_id` should also be null for `sequencing_center`  to support harmonized genomic_files. Below is the current scenario of our model. i did not quite understand the use case where there is no relationship between  `study` and `genomic_file`.  does that mean `genomic_files`
 are also null for harmonized genomic files in `biospecimen` entity? 
![screen shot 2018-04-30 at 5 03 03 pm](https://user-images.githubusercontent.com/20447220/39450181-695302b8-4c98-11e8-87ca-d66d7f8c4c36.png)

**Comment by znatty22** [comment]
The consensus is that we will make the foreign key `sequencing_experiment_id` on genomic_file nullable.
