### ISSUE TITLE
Study ID  and Bam files for the project ready to run

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-api-dataservice#280]
Priority | FY | X01 | Sequencing Center | Est Release Date (NIH) | dbGaP Study ID | DRC Status
-- | -- | -- | -- | -- | -- | --
2 | 15 | Schiffman** | WashU | 11/1/17 via KF TP | phs001228 | Not Loaded
2 | 15 | Chung & Shen | Baylor | Released 5/25/17 via dbGaP | phs001110 | Not Loaded
2 | 15 | Engle | Baylor | Not yet released via dbGaP | phs001247 | Not Loaded
2 | 15 | Seidman & Gelb | Baylor | Released 11/13/17 via dbGaP | phs001138 | Not Loaded
2 | 16 | Chung*** | Broad | June 1st, 2018 via KF TP | phs001110 (would be a Version 2) | Not Loaded

Does anyone know where are this projects' SD id and where are the bam files ready to run the harmonization ?

**Comment by dankolbman** [comment]
Issue moved to [kids-first/kf-study-imports #5](https://github.com/kids-first/kf-study-imports/issues/5) via [**ZenHub**](https://www.zenhub.com/)
