### ISSUE TITLE
Parameters description of phenotype patch API seems wrong

### ISSUE THREAD

**Issue by grugna** [kids-first/kf-api-dataservice#306]
http://kf-api-dataservice-qa.kids-first.io/#tag/Phenotype%2Fpaths%2F~1phenotypes~1%7Bkf_id%7D%2Fpatch

There are parameters missing (ex: 'hpo_id_phenotype') and there are extra param that have nothing to do with the phenotype entity

**Comment by dankolbman** [comment]
Looks like the demographic model is being munged into all of the patch methods.
