### ISSUE TITLE
Proper use of custom fields

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#311]
For any custom marshmallow field on a model schema, we should use field_for(field_class=<custom field class here>).

Needed so that field_for can figure out how to set the required/allow none properties based on the column properties.

- [ ] experiment_date in sequencing experiment
- [ ] shipment_date in biospecimen

**Comment by dankolbman** [comment]
Not really sure if this is proper seeing as it's not documented anywhere in the marshmallow-sqlalchemy docs...

**Comment by znatty22** [comment]
Ooook maybe not "proper" per say, but I think we should still do it bc it allows us to reuse marshmallow logic to set those booleans (allow_none, required) rather than manually set them (or forget to set them)

**Comment by znatty22** [comment]
Actually I'm really surprised its not documented
