### ISSUE TITLE
sequencing-experiments filtering by study_id returns 0 results

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-dataservice#323]
`/sequencing-experiments?study_id=SD_9PYZAHHE` returns 0 results when I can see that there are sequencing-experiments for the study, because I can work around to them from the other side by visiting `/biospecimens?study_id=SD_9PYZAHHE` and then choose one of the biospecimens in the study and then see the specific sequencing center used for that specimen and then I can see sequencing experiments from my study.

**Comment by parimalak** [comment]
its the same with `/diagnoses?study_id=SD_9PYZAHHE` i get 0 results.

**Comment by fiendish** [comment]
That might be ok because this study doesn't really have diagnoses.

**Comment by parimalak** [comment]
yeah but we have applied study filter for all entities. see #230

**Comment by fiendish** [comment]
I mean that I don't think that there are any diagnosis entities uploaded for any participant in this particular study, so even if the filter is working for diagnoses I think it would still return 0 results for SD_9PYZAHHE.

/diagnoses?study_id=SD_5VC8QC50  does return results.

Now the weird thing is that /sequencing-experiments?study_id=SD_5VC8QC50 also returns results.

Could the issue be that SD_9PYZAHHE doesn't have any genomic files uploaded yet and SD_5VC8QC50 does?

**Comment by znatty22** [comment]
@fiendish thats correct. The only way to get sequencing experiments for a study is that they have to be linked to genomic files. Otherwise the seq experiments are just orphan entities, since they're not linked to anything else. Same goes for sequencing centers

**Comment by fiendish** [comment]
Got it. Thanks @znatty22 !
