### ISSUE TITLE
API returns 200 even when incorrect parameter is used

### ISSUE THREAD

**Issue by parimalak** [kids-first/kf-api-dataservice#326]
For example, `/diagnoses?categoty=test` returns 200, API should return 400.

**Comment by znatty22** [comment]
Yea, so this is actually default behavior of the filter parameter validation (webargs/marshmallow). I don't know what the desired behavior should be, if we want to return a 400 here or just keep it to what it is? If the former, then ill have to do some research to see if thats possible with marshmallow

**Comment by znatty22** [comment]
Actually...thinking about it 🤔 , and pretty sure in dataservice, we reject unknown fields using marshmallow validators in the base schema. All the filter parameter schemas inherit from this so now I'm wondering why it doesn't reject those fields...
