### ISSUE TITLE
read group metadata for source file in FASTQ format

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-api-dataservice#343]
The genomics harmonization team needs to know the read group information such as `paired_end*, read_group_name*, library_name, flow_cell_barcode, platform, sequencing_center, read_length etc` (* are required) for fastq inputs to be able to run the alignment workflow properly. Required a data model for `Read Group` like the one [GDC](https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=read_group) has. 

Currently most GMKF sequencing center provided BAM file which has the Read Group information embed as part of the file header, but the BAMs that HudsonAlpha provided are with incorrect header, we are planning to run the workflow from FASTQ for those data. In addition to that, about 40% of the CBTTC source data are in FASTQ format. To have this model ready, so help the system to have the ability to take FASTQ files from other data generators. 

Suggested model:
- GDC: https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=read_group
- CBTTC: https://github.com/d3b-center/cbttc-bank-seq/blob/master/sqlite/initial_csv/cbttc_fastqs.csv

**Comment by dankolbman** [comment]
We currently use the `SequencingExperiment` model to store summary statistics about genomic files in the data model. Perhaps we should consider having another model to store the read group metadata for a genomic file with these fields.
