### ISSUE TITLE
standard "file_format" value for /genomic-files

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-api-dataservice#347]
The genomics harmonization team was trying to GET gvcf file information from `/genomic-files`, it used to return `gVCF` as `file_format`, then at one point it was `gvcf`, just found out this morning, it's `gVCF` again, this confused our script, we can probably just a do regex match to fix this specific case, but it’d be nice to have a standardized/recommended or name convention for the `file_format`, so that we can better interactive the api.

**Comment by dankolbman** [comment]
The `file_format` should always follow these enums from now on: https://github.com/kids-first/kf-api-dataservice/blob/master/dataservice/api/genomic_file/schemas.py#L10-L18
This is a recent addition, so things weren't always standard.

**Comment by yuankunzhu** [comment]
ah nice, it's ok they weren't always standard at beginning. but at least we know where to check the enums now, thanks.
