### ISSUE TITLE
"total" field ignores "after" query parameter

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-dataservice#360]
http://localhost:1080/family-relationships returns
```
{
  "_links": {
    "next": "/family-relationships?after=1526067434.567431", 
    "self": "/family-relationships"
  },
...
  "total": 3157
}
```

http://localhost:1080/family-relationships?after=1526067434.567431

returns the same "total" value, which is not the 3147 I would expect.

**Comment by fiendish** [comment]
I'm not marking it a bug, because the correct behavior is uncertain. I was just thrown by it.

**Comment by znatty22** [comment]
hey @fiendish so `total` refers to the total number of entities in the db for the given query. It takes into account query parameters excepting `after` and `limit` which are special query parameters for paginating through the objects in a query. 

So for example lets say there are 200 participants and 50 of them are probands. `/participants` should return total = 200 and `/participants?is_proband=True` should return a total = 50. 

If the above behavior is not happening, then that is probably a bug.
