### ISSUE TITLE
Multiple Biospecimen to Genomic Files Modeling/Ingestion

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#363]
For VCF files (call sets), we're currently targeting two cases:

- Family-level (mostly trio) joint genotyping, where each VCF contains the variants for each family
- Study-level joint genotyping, where each VCF contains the variants for all participants in the study

In the future we may look into DRC-wide call sets that contain all participants. 

In theory, each of these should contain all of the samples for their levels, but in practice there are a number of reasons where we might generate the CRAM/gVCF but not want to include them in the final call set. Including:

- Duplicate samples (currently occurs in CBTTC)
- Low quality samples 

So we want to be able to track specifically what samples where used. 

With current model, for harmonized files this is possible via following all of the `cavatica_task_genomic_files`. However, this is currently not being populated and there is potential of receiving unharmonized genomic files that we may want to map back to the specific biospecimens as well. This would require supporting many to many between biospecimen and genomic file.

**Comment by allisonheath** [comment]
Also to add, another use case coming up are tumor/normal pairs where both the data for a tumor specimen and a normal specimen are used as imput.

**Comment by parimalak** [comment]
After discussion with @znatty22 @fiendish and @liberaliscomputing we decided to do the following changes:

Make biospecimen to genomic file relationship many to many by creating association table between biospecimen and genomic file called `biospecimen_genomic_file`
This model change going to cover cases like tumor/normal and pooled biospecimens(#264 ) that are being sequenced together.

There are currently two cases to consider for ingesting the genomic files from joint genotyping.
  **Case 1: Migration for data already in Production**

1. Create table `biospecimen_genomic_file` and populate with biospecimen id/s and genomic file id/s
2. Make bs_id nullable in genomic file?
3. Drop `biospecimen_id` column from genomic file
4. Remove `bs_id` tags or no longer update `bs_id` tags

**Case 2: Ingesting new data in Production**

As yuankun team will no longer able to tag the multiple biospecimens on s3 objects. `Cavatica_task` table needs to be populated either by yuankun’s team or by data engineering team. If data engineering team is responsible, we will have to check cavatica for the list of source genomic files and find their respective biospecimens from data service and update `biospecimen_genomic_file`, `genomic_file` and `biospecimen` tables.

**Comment by dankolbman** [comment]
Why do `bs_id` tags need to be dropped? They can still be used to associate genomic files originating from a single biospecimen.
All other genomic files can resolve to a a biospecimen by traversing back through CavaticaTask to the original CRAMs and gVCFs.

It seems like this is a good use case for using a recursive view, that way we can avoid a messy migration and a less complicated insertion operation.

**Comment by allisonheath** [comment]
I think it's quite likely we'll be asked to distribute files with multiple biospecimens (e.g. VCFs from the sequencing centers) which don't have CavaticaTask. Also, if the paths to the final GenomicFile get long with many biospecimens, that traversal can have serious performance issues.

**Comment by parimalak** [comment]
@dankolbman we are going to keep tagging the bs_id/s.  @allison @yuankunzhu suggested a way to get all biospecimen id's from vcf/s without populating `cavatica_task` table. Yuankun's team include all the biospecimens used in the header of VCF; we need to scrap the s3 objects based on the basename to obtain the all genomic files from a `cavatica_task` and read vcf header for biospecimens. Finally update the relationships between `genomic file` and `biospecimen`

**Comment by allisonheath** [comment]
@parimalak sounds good, we might need to do the same reading of the header for the VCFs from the sequencing centers to get the IDs - except they'd match the external biospecimen IDs

**Comment by junjun-zhang** [comment]
So we had a discussion here from ETL point of view. The change proposed here (ie, introducing a new table to support many-to-many relationships between biospecimen and genomic file) would require some changes in the ETL but it should be OK.

One related topic is that the JSON document for file-centric index might get `too big` when a genomic file links to very large number of participants/specimens. This is something we probably should discuss and come up with suitable solutions later.
