### ISSUE TITLE
Data Model Changes for Advanced Families & Affection Status

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#391]
List of Changes:
1. Add Affected Status (boolean) to participant
    1. Rule: If its a perfect trio, we can assume that the proband is affected.
2. Add family type (enum?) to family - we will start calculating the family relationships and we can calculate as trio, duo, etc. For example - Engle will be trio+
3. Make is_proband on participant nullable (in the event that we have affected status but not proband infO)
4. Add Source_text_notes (or similar) to family_relationship

**Comment by parimalak** [comment]
@allisonheath  what are the enums for family_type? Only `trio`, `duo`, `trio+`?

**Comment by allisonheath** [comment]
`Proband Only`
`Duo` (one of mother or father and proband)
`Duo+` (one of mother or father and proband and one or more other family member)
`Trio` (mother and father and proband)
`Trio+` (mother and father and proband and and one or more other family member) 
`Other` (anything that doesn't fit in one of the above categories)

**Comment by baileyckelly** [comment]
We should use Engle in QA to load as "test data" for OICR to test their ETL with.
