### ISSUE TITLE
Add 'visible' field to entities

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#397]
We need the ability to partially release and ETL studies. For example, the multi-year studies that share the same study id. 

After discussions, the best way to do this is on the Biospecimen.

Notes from conversation during sprint planning back in May:
Study Discussion
•	Need a way to load data but not show it on the portal.
•	Idea: Put release date on sample? Only show participant if they have a previously released sample. 
o	We should have a release iD rather than a release date because release dates change.
•	Current decision: Studies will be 1:1 with dbGaP. Need to fix Chung.

**Comment by dankolbman** [comment]
The `visible` field should be a `Boolean` column on the base model.

This will be used in the future for visibility of data from the dataservice api where only administrators and the study investigator may view data that is `visible=False`.

**Comment by baileyckelly** [comment]
Decision:
We should put this column on every table.
Values will be True/False

For now, with the data ingest, we will focus on toggling the biospecimen & the file level. However, we see cases in the future where we may want to toggle Phenotype, for example.

dbGaP manages access at the biospecimen level, which will be the primary use case.
