### ISSUE TITLE
CBTTC: Need an Additional ENUM Value for RSEM

### ISSUE THREAD

**Issue by liberaliscomputing** [kids-first/kf-api-dataservice#400]
@yuankunzhu told me that at least either `Expression` or `Expression Data` is need to tag `data_type` of RSEM files. Temporarily, I populated `Other` to it. See also kids-first/kf-study-imports#92.

**Comment by allisonheath** [comment]
Here are the categories used by GDC - do you think they fit here? @yuankunzhu 

<img width="343" alt="screen shot 2018-08-03 at 12 23 02 pm" src="https://user-images.githubusercontent.com/2213854/43654059-0b8c7d88-9718-11e8-92db-4e19102fa8a9.png">
