### ISSUE TITLE
Add pathology slide and report files

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#403]
The current use case is CBTTC - but many cancer cohorts have pathology slide images. In reality, they are generated from a slice of a biospecimen and this is how they're modeled in the GDC. See https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=slide

However, CBTTC does not track the biospecimens they were generated from, but rather the diagnosis or "clinical event" they were associated with. 

There is also a deidentified PDF report by the pathologist of their findings.

**Comment by dankolbman** [comment]
Closing with #404 #409 #444 et al while we consider other representations.
