### ISSUE TITLE
Add MRI and report files

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#404]
The main use case currently is CBTTC - they main MRIs of interest are those taken pre and post surgery. In CBTTC parlance this is associated with a "clinical event" which is typically associated with a diagnosis. Additionally, patients often have many MRIs over time to monitor status and these may be added at a later time.

There is also a deidentified PDF report associated with the radiologist finding from the MRIs.

**Comment by dankolbman** [comment]
Closing this with #409 #450 et al while we investigate alternative models.
