### ISSUE TITLE
Implement Imaging Model

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#409]
We need to be able to represent and store:

1. MRI Images - which are attached to the participant
2. Path Slides - which are attached to the biospecimen
3. MRI Reports which are attached to the MRI
4. Path Reports - which are attached the the path slide.
5. Op reports 

Tasks:
-Define models needed 
-Implement Models
-Import data
-Make ETL Changes

**Comment by dankolbman** [comment]
These should be individual issues.

**Comment by baileyckelly** [comment]
This ticket is an Epic. :) Was using this to outline the other tickets that would get created underneath it.

**Comment by dankolbman** [comment]
Closing with #444 and #450 as we are going to consider alternative models
