### ISSUE TITLE
Change ReadGroup to GenomicFile relationship: 1-1 --> many to many

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#411]
Right now there is a 1 to 1 relationship between read group and genomic file. We need to change it to 1 read group to many genomic files. 

In the Rios/Wise study, I have 1 read group that related to 2 fastq files. I need to be able to relate these two fastq files to the same read group.

And just to reiterate from previous discussions on read groups, we are not associating all read groups to their resulting bam. Instead we're linking any read group metadata a fastq has back to the read group.

**Comment by znatty22** [comment]
To be aware of: 
- This is a blocker for importing Rios/Wise - https://github.com/kids-first/kf-study-imports/issues/123
- Will need to write a migration for existing read groups as well
- Will need to move `paired_end` field from read group to genomic file

**Comment by allisonheath** [comment]
Talked with @yuankunzhu, this is the right direction to go. He actually supports the idea of it being many to many to support direct relationships with read groups in the future. Not sure if it's easier to do that now or do it in two steps as we don't have an immediate need to support read group -> BAM.
