### ISSUE TITLE
Support upsert operations

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-dataservice#419]
If a client says "please note that there is a relationship between A and B", why will the server ever respond "YOU MADE AN ERROR: I already think that there is a relationship between A and B"? I think it should just say ok and then either do nothing or update the timestamp.

**Comment by dankolbman** [comment]
We considered the upsert option early in the dataservice's life. There were some difficulties that made it non-trivial to implement. If you'd like to look into it further, it would be much welcomed.
