### ISSUE TITLE
Soft deletion of entities

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-dataservice#423]
In light of the fact that biospecimen KFIDs are being embedded into harmonized genomic files, to ensure that we don't accidentally run into KFID conflicts by having entities removed and then re-added with potentially reused-in-the-meantime IDs, DELETE API calls should just set visibility to false.

Any actual deletion should happen only internally and not by external API.

**Comment by junjun-zhang** [comment]
I like this idea. To take the point further, maybe deletion should not even be allowed internally. As mentioned above, biospecimen KFIDs are embedded in genomic files, these are like foreign keys. If the primary key is deleted, foreign keys would become orphaned.

Of course, although likely unusual, if one is sure a freshly created biospecimen KFID has never been used anywhere else, it should be safe to delete.

**Comment by dankolbman** [comment]
Soft deletes do sound like a good idea, but I'm not convinced that deletes should be removed all together. There are certainly situations where we will want all traces of something to be removed.

The removing-re-adding process shouldn't be happening anymore once the visible field has been utilized properly. 

We should also consider the case where some import processes currently work by creating fresh entities, which are then manually dropped and reloaded with no regards to their former kf_id. We could quickly endup with many unused orphans with no way resolving where they came from, or if they are duplicates.

**Comment by dankolbman** [comment]
Also, this should be a general feature if implemented, not restricted to only participant/biospecimen.

**Comment by allisonheath** [comment]
👍 from me as well. 

I could see having both the soft and hard deletes in the API, especially when we're in initial loading/debugging mode the hard deletes are useful.

If/when we get to better auth and user roles, I could imagine hard deletes requiring escalated permissions.

**Comment by fiendish** [comment]
Implementation-wise, I think we will need to store a dummy variant of every kind of parent entity for this so that we can satisfy foreign key requirements on the moved entities.

**Comment by allisonheath** [comment]
The only second thought I really have is the potential of performance issues. If people are deleting/reloading a lot we might get very large tables with the potential to cause issues if joins aren't carefully thought out.

**Comment by dankolbman** [comment]
@allisonheath this shouldn't affect join performance at all unless there are intermediate filters on non-indexed fields (currently not supported by the api anyway)
