### ISSUE TITLE
/diagnoses?biospecimen_id=foo gives wrong/unrelated results

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-dataservice#425]
Notice below that:
* three different participants are returned for one biospecimen_id (BS_Q5AH9TH0)
* none of them are the participant actually associated with that biospecimen (PT_YT70KJ5P)
* it is using the default limit=10 but gives 4 results, though the total field says 2744 (the total number of all diagnoses, queried without any filter, is given as 8690)

<img width="504" alt="screen shot 2018-08-27 at 3 15 08 pm" src="https://user-images.githubusercontent.com/201996/44680722-8dcaae80-aa0c-11e8-8b80-4e59c3129dca.png">

<img width="822" alt="screen shot 2018-08-27 at 3 15 03 pm" src="https://user-images.githubusercontent.com/201996/44680727-90c59f00-aa0c-11e8-8767-8ca8673881d0.png">

<img width="308" alt="screen shot 2018-08-27 at 3 21 23 pm" src="https://user-images.githubusercontent.com/201996/44680848-e26e2980-aa0c-11e8-982e-c942e513edc3.png">

<img width="747" alt="screen shot 2018-08-27 at 3 21 53 pm" src="https://user-images.githubusercontent.com/201996/44680876-f2860900-aa0c-11e8-9d66-3888293d3c1b.png">

**Comment by fiendish** [comment]
@parimalak is this fixed or just closed?

**Comment by znatty22** [comment]
I tried it with a couple of @liberaliscomputing biospec, diag combos and it seemed to work well, but I think @liberaliscomputing should check it out as well and make sure. I'm reopening this issue until we know its def fixed.

**Comment by fiendish** [comment]
fixed by what pr/commits?

**Comment by znatty22** [comment]
#416. Its already merged into QA

**Comment by fiendish** [comment]
@liberaliscomputing can you confirm?

**Comment by liberaliscomputing** [comment]
Let's close this ticket since it is resolved.
