### ISSUE TITLE
we need a faster way to clear old phenotypes and diagnoses from the dataservice

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-dataservice#428]
Participant and biospecimen ids need to be locked down, but phenotypes and diagnoses are things that we get wrong and need to fix/drop/replace all the time. Since there can be many many thousands of these per study, deleting them one at a time is not reasonable. I would like a way to drop all phenotype/diagnosis entities under a given study, a number that may measure in the tens of thousands, that completes in seconds instead of hours.

**Comment by znatty22** [comment]
Hmm I'm on the fence about this. Without auth on the dataservice, if we had an endpoint that allowed a drop all, it seems like it would be too easy to accidentally wipe out all the phenos or diagnoses...

**Comment by fiendish** [comment]
auth is 100% critical and needs to happen sooner rather than later, but doesn't have any impact on this. At the very least I need to be able to do it in QA.

**Comment by dankolbman** [comment]
We could adapt the DELETE method in the api to also accept a json body of { "kf_id": [ ... ] } so that you could delete many per request. This should speed things up by reducing the http overhead.

**Comment by fiendish** [comment]
@dankolbman assuming the server doesn't kill the backend process if it decides it needs to take longer than a few seconds (see the 500 errors on study deletion issue), that would probably cover it

**Comment by dankolbman** [comment]
The time to perform `DELETES` against the database is extremely small, assuming that it's done in batch on the db without serializing to python.
The timeouts come from having to serialize a large amount of data coming out of the db.

**Comment by znatty22** [comment]
The biggest bottle neck on DELETE study was actually all of the calls out to Gen3 when deleting gfs. The second bottleneck was what @dankolbman said. Serializing all of the db rows to python objects in memory. I agree, if we just batch delete on the DB then it should only take seconds, maybe up to a minute max.

**Comment by fiendish** [comment]
> The biggest bottle neck on DELETE study was actually all of the calls out to Gen3 when deleting gfs. 

Doing this is a huge logical error. Removing something from the dataservice shouldn't touch gen3. The entire point of gen3 is _permanence_. Gen3 links should only go away if the file physically no longer exists anywhere.
