### ISSUE TITLE
Automatic deletion of orphaned genomic files

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#429]
Now that we have a many to many relationship between biospecimens and genomic files, we don't have a cascading delete from biospecimen to genomic files. But perhaps we should? 

We can handle this the same way we do with families, sequencing experiments, and read groups. Could add a delete event listener on the biospecimen. On biospecimen delete events, check if there are any orphaned genomic files and delete them if there are. 

Thoughts?

**Comment by dankolbman** [comment]
Part of the reason we removed the cascade was to allow us to register files for download that didn't have a place otherwise.
Are we sure we won't come up against this issue in the future?

**Comment by znatty22** [comment]
What does that mean? We want to be able to have files that are not connected to any biospecimens?

**Comment by dankolbman** [comment]
Right. Or populate them before there is information about biospecimen.

**Comment by znatty22** [comment]
Ok I see. And actually I now vaguely remember @allisonheath or @liberaliscomputing  saying something about  wanting to create genomic files without biospecimens? Which we can do right now, since the biospecimen_id foreign key on genomic file is nullable. So maybe we do want to keep what we have now
