### ISSUE TITLE
Create MVP ERD

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#43]
Note: This is due EOD Thursday 1/25/18

We need to create an ERD for OICR of the MVP entities

* Participant
    * Rename Person to Participant
* Sample
* File
* Demographic
* Diagnosis
* ~Participant Relationships 
    * (Needs spec’d out)
* ~Phenotype 
    * Just HPO ID
    * Age at observation (Optional)
* ~Dataset
    * Needs spec’d out
* ~Outcome/Encounter/Event
    * Needs to be spec’d out

**Comment by allisonheath** [comment]
Initial pass:
[DataModelMVP-20180125.pdf](https://github.com/kids-first/kf-api-dataservice/files/1664754/DataModelMVP-20180125.pdf)
[DataModelMVP-20180125.xml.zip](https://github.com/kids-first/kf-api-dataservice/files/1664755/DataModelMVP-20180125.xml.zip)

For now, left off types, but in general should be straightforward. The idea is to first get current data in hand into as-is (no enums for example) and that will give a baseline of where to focus harmonization efforts.

For sure we'll be iterating on this, and ultimately #40 will have all of the details, but this is to give an initial goal to works towards. Feedback welcome! 😄

**Comment by allisonheath** [comment]
Also to further expand on the harmonization and the large arrows to the various ontologies and where we're generally headed at the moment:
 
For example, for phenotype right now we're just going to put the phenotypes we're directly getting to the investigators into the `phenotype` field as a string (e.g. `WEBBED_NECK`). Then we'll work on the analysis on how to harmonize those to HPO terms and likely create a `HPO_ID` field where that ID will be stored (e.g. [HP:0000465](http://compbio.charite.de/hpoweb/showterm?id=HP:0000465)) . The dataservice then can use that ID to materialize the standard term name out via the API, along with other features as needed such as synonyms, lay terms, hierarchies, xrefs as needed. 

Similar concept for diagnosis and MONDO, anatomic site and UBERON, etc.

**Comment by allisonheath** [comment]
From conversations today, the only immediate change is adding `tumor_descriptor` to the sample entity. There were some suggestions on how to improve the family structure, but need to understand some more use cases to determine best path forward. Same for the study/dataset structure. Will open other tickets for those two. I think we can call this closed for the initial pass.
