### ISSUE TITLE
Spec out / Design Imaging Models

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#444]
We currently have images loaded in the data service as genomic files. This was a short term work around. We need to properly build out the imaging models to handle these data types. 

#### Data Types we currently have
* Pathology Reports (pdfs)
* Histology Images (Path Slides): The staining is currently stored in the image name (svs)
* MRI Images (Pre,Post op - in name. Has body location in name) (dicom - stored in S3 as zips)
* MRI Reports (pdfs) (Pre,Post op - in name. Has body location in name)
* Operations Reports (pdfs)

#### There is meta data that we need to store about these images.
* Review the Cancer Imaging Atlas
  * They have metadata standards that would be nice to align with.
* Pathology - Currently have just stain type.
* metadata in the dicoms
* path reports/histology images are assigned to a virtual biospecimen
* MRI/radiology should be attached to the participant.

We also need a migration plan to handle the images that we currently have stored as genomic files.
What do we do with all the used GF ids?

**Comment by fiendish** [comment]
> What do we do with all the used GF ids?

I vote to elevate https://github.com/kids-first/kf-api-dataservice/issues/431 to urgent priority and block this task until that one is resolved.

**Comment by dankolbman** [comment]
#431 does not block the design of the imaging models. It may block the application of it, though.

**Comment by allisonheath** [comment]
Can we do this in parallel? 

I agree that #431 is becoming urgent priority, but it shouldn't block creating the spec out for what the data model should look for imaging files. We could even keep the imaging files in GF and mark as not visible (obviously not ideal).

Could I suggest at least two people take on the design for this and at least two people take on the design for #431 and then we can do a review session across the two?

**Comment by parimalak** [comment]
#403 we might need to add some of this metadata for pathology slide model.

**Comment by dankolbman** [comment]
I'm going to close with #450 and #409
