### ISSUE TITLE
Standardize many-to-many entity endpoints

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#449]
Currently each entity in the DB has a set of endpoints that expose CRUD operations on that entity. The fields allowed in read filter params, or bodies of posts and patches all map directly to columns in the table for that entity. This makes it very easy and straightforward to interact with the entity. 

Two of the many-to-many association tables do not follow this standard (read_group_genomic_file and biospecimen_diagnosis). For automated processes such as data ingestion and portal ETL, this is not ideal because different logic is needed to create, read, or update biospecimen_diagnoses and read_group_genomic_file entities. 

We need to change the endpoints for these entities so that they follow the same standard as the others.

**Comment by allisonheath** [comment]
I think we should bump this up in priority - would be good to do before the ETL gets to https://github.com/kids-first/kf-portal-etl/issues/34 (which I think should be soon cc @rosibaj @baileyckelly ?)

**Comment by parimalak** [comment]
Addressed in #453 , #455
