### ISSUE TITLE
List Desired Enums

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#48]
Participant Fields
- [ ] Race
- [ ] Gender
- [ ] Ethnicity

Diagnosis Fields
- [ ] diagnosis_category

**Comment by parimalak** [comment]
release_status of study

**Comment by allisonheath** [comment]
Idea is to put this in the Marshmallow enums on the application layer so it's easier to adjust than on the database layer.

**Comment by parimalak** [comment]
can we make these columns to enums?
- [ ] vital_status in outcome (Dead, alive or Not Reported)
- [ ] availability in genomic_file and study_file(available for immediate download, cold storage, unknown)
