### ISSUE TITLE
Include upstream files in GenomicFile roll-ups

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-dataservice#482]
The `GenomicFile` contains a handful of roll-up fields for `SequencingExperiment`. These are currently populated with that `GenomicFile`'s immediate `SequencingExperiment`, but should also include the `SequencingExperiment`s of any upstream files.

Eg, using the `experiment_strategies` field:
```
File A: ['WGS']
File B: ['WXS']
File C, Derived from A, B: ['WXS', 'WGS']
```

**Comment by allisonheath** [comment]
`Upstream files` are ones that connected via tasks.
