### ISSUE TITLE
Require jenkins to pass before allowing a PR to merge

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-api-dataservice#495]
Looking through the history, I see several merged PRs that fail whatever it is that Jenkins is trying to do. What's the point of having the check if we're just going to ignore it?

**Comment by allisonheath** [comment]
Can you point me to a few of the PRs and associated Jenkins jobs?

**Comment by fiendish** [comment]
#492  is one

**Comment by fiendish** [comment]
https://github.com/kids-first/kf-api-dataservice/pulls?utf8=✓&q=is%3Apr+is%3Amerged+status%3Afailure

`is:pr is:merged status:failure`
