### ISSUE TITLE
Create Initial Phenotype Model

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#51]
*User Story*
As a Kids First developer, I would like basic CRUD functionality to work with Phenotypes. Note - this needs to be spec'd out from a data model perspective. 

*Tasks*
- [ ] Create Model
- [ ] Resource
- [ ] API: Put, Patch, Delete, Get

*Acceptance Criteria*
Documentation
Have Put, Patch, Delete, Get
Unit Tests - Tests on Model, Resource, API

**Comment by allisonheath** [comment]
In addition to the fields in the MVP in #43, need a field that indicates whether it's a positive observation (the participant has the phenotype) versus whether it's a negative observation (it was reported the participant does *not* have the phenotype) versus just not reported (participant may or may not have the phenotype).

Per conversation today the fields are:
- `phenotype`: as-is from the source files
- `hpo_id`: the HPO ID that we mapped the source phenotype to
- `observation_status`: one of `positive` (phenotype was positively observed), `negative` (phenotype was negatively observed) or `not reported` (unknown whether was observed)
- `age_at_event_day`: the days at which it was observed (if known)
