### ISSUE TITLE
Create initial Dataset Entity

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#52]
*User Story*
As a Kids First developer, I would like basic CRUD functionality to work with a Dataset. Note - this needs to be spec'd out from a data model perspective. 

*Tasks*
- [ ] Create Model
- [ ] Resource
- [ ] API: Put, Patch, Delete, Get

*Acceptance Criteria*
Documentation
Have Put, Patch, Delete, Get
Unit Tests - Tests on Model, Resource, API

**Comment by allisonheath** [comment]
Should the dataset entity cover the dbGaP project entity use case in #22 ?

**Comment by dankolbman** [comment]
I'd say no. Dataset should ultimately be defined by the contributor and define the context and scope of the batch of data that they are contributing. the dbGap project could be an external relation and may optionally define some access patterns to a dataset, but a dataset should not be required to have one-to-one.

**Comment by allisonheath** [comment]
Hmm I think more generic question is does grouping data into a dataset convey anything else other than who contributed them? For example, does the contributor "own" the dataset and who is authorized to have access? If they do, then you can almost think of dbGaP projects as particular instances of datasets where the contributor is dbGaP who is controlling the authorization. 

And secondarily, does "data" in the dataset just encompass files (well objects in S3)? Or does information extracted out of the files count? My initial thought was the former, but I could see both ways.

**Comment by dankolbman** [comment]
We've created `study` #130 which essentially captures the same data as the dataset concept discussed here.
