### ISSUE TITLE
Need New Enum Types for SE and GF

### ISSUE THREAD

**Issue by liberaliscomputing** [kids-first/kf-api-dataservice#521]
Referring to kids-first/kf-study-imports#571, we need new enum types for `experiment_strategy` and `platform`:

- [x] `experiment_strategy`: `BAC32K` and `450K` >> `CGH Array` and `Methylation Array`
- [ ] `platform`: `BlueGnome`

And, on top of `BAM`, Open DIPG has new file formats, `GPR` and `IDAT`, they may need new `data_type` for GF (https://kf-api-dataservice.kidsfirstdrc.org/#tag/GenomicFile%2Fpaths%2F~1genomic-files%2Fpost).

**Comment by yuankunzhu** [comment]
To me, the `experiment_strategy` should be methylation/CGH array for this analysis:
```
| \                   | BAC32K          | 450K                           | 
|---------------------|-----------------|--------------------------------| 
| experiment_strategy | CGH array       | Methylation array              | 
| platform            | Agilent 32K BAC | Illumina Human Methylation 450 | 
```

pinging @jharenza and @kgaonkar6 as they are actively working on this data.

**Comment by liberaliscomputing** [comment]
Thanks @yuankun! Per `platform`, we have used merely `Illumina` and can `Illumina Human Methylation 450` be shortened as well? I wonder if `Agilent 32K BAC` could also have a shortned form.

**Comment by jharenza** [comment]
@liberaliscomputing and @yuankunzhu - we have to capture the type of array here somewhere. if you shorten platform to `Illumina` and `BlueGnome` (not Agilent, I don't think), then BAC32K and 450K and later, 850K will have to be in `experimental_strategy` - it is really how you want to handle the data

**Comment by jharenza** [comment]
@liberaliscomputing - let's use what @yuankunzhu wrote above - no shortening platform

**Comment by yuankunzhu** [comment]
two references: 
- GDC: https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=methylation_beta_value
- SBG: https://docs.sevenbridges.com/docs/metadata-on-the-seven-bridges-platform

**Comment by allisonheath** [comment]
I concur that we should use the values @yuankunzhu proposed - and thanks for the references.

**Comment by liberaliscomputing** [comment]
@allisonheath, @jharenza, and @yuankunzhu, any suggestions for new `data_type` enums for `GPR` and `IDAT` (https://kf-api-dataservice.kidsfirstdrc.org/#tag/GenomicFile%2Fpaths%2F~1genomic-files%2Fpost)?
