### ISSUE TITLE
Create Initial Outcome Model

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#53]
*User Story*
As a Kids First developer, I would like basic CRUD functionality to work with an Outcome/encounter/event. Note - this needs to be spec'd out from a data model perspective. We also need to define the name.

*Tasks*
- [x] Create Model
- [ ] Resource
- [ ] API: Put, Patch, Delete, Get

*Acceptance Criteria*
Documentation
Have Put, Patch, Delete, Get
Unit Tests - Tests on Model, Resource, API

**Comment by allisonheath** [comment]
Fields:
`vital_status`: Alive, Dead, Not Reported
`disease_related`: true if Dead and cause of death was disease related, false if Dead and cause of death was disease related, Not Reported
