### ISSUE TITLE
Add `library_selection` and `library_prep` field to SequencingExperiment

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#540]
The `library_selection` enums can come from GDC: https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=read_group

@jharenza @yuankunzhu what values do you want `library_prep` to be able to accept? The only one I have is `polyA` - also maybe could you give a bit of a description we can use in the field description?

**Comment by jharenza** [comment]
@allisonheath if you use `library_selection` and the enums they have, you can also use `library_strand` and between the two, we can determine the library prep as a general stranded or polyA. Would that work?

**Comment by jharenza** [comment]
While I am thinking about it, do you have all allowable values for `library_strategy`? We do have two `Targeted Sequencing` samples in PNOC, `BS_7KR13R3P` and `BS_WHZT48VG`.

**Comment by allisonheath** [comment]
@jharenza ok so since we already have `library_strand` so we just need to add `library_selection` with the same values allowed as GDC?

For `library_strategy` - we actually don't have it because it seemed redundant with `experiment_strategy`, which right now allows:

- WGS
- WXS
- RNA-Seq
- miRNA-Seq
- Linked-Read WGS (10x Chromium)
- Other

Should we add `Targeted Sequencing` as well?

**Comment by jharenza** [comment]
@allisonheath yeah, that's what i meant -  your `experimental_strategy`. We should add `Targeted Sequencing` - I think that sample is labeled as WXS by mistake. We should also add `array` perhaps for non-sequencing?

For `library_strand` - are those already entered for every patient or do you need those from us after processing? I would say yes to just adding `library_selection` then.
