### ISSUE TITLE
New field to distinguish human and canine participants

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#542]
We have canine data incoming, so participant needs a new field that takes two values:
`Homo sapiens` (default)
`Canis lupus familiaris` (domesticated dog)

My initial thought was to call this `species`, but really the latter is a subspecies, so was considering calling this field `taxonomy`? Or any other good options for this?

cc @nicolevasilevsky perhaps?

**Comment by nicolevasilevsky** [comment]
+1 to taxonomy. We use NCBI taxonomy for organism annotations.

**Comment by allisonheath** [comment]
Ok great @znatty22 let's go with `taxonomy`. 

@nicolevasilevsky as in https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=9615 right?

**Comment by nicolevasilevsky** [comment]
Yes, exactly!

**Comment by znatty22** [comment]
Completed
