### ISSUE TITLE
Fix Participant put and delete methods in resource class

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-dataservice#57]
Problem: 
When trying to put/delete a participant that does not exist (kf_id does not exist in db), an exception is thrown because these methods are not returning when they should be.

Solution:
Add return statement before self._not_found() method in both put and delete methods in:
dataservice.api.participant resources.py

Validate:
Write tests for put and delete to verify that put/delete for a kf_id that does not exist, will return the correct response (content and code = 404)

Example code change:

```python
@participant.expect(participant_fields)
    def put(self, kf_id):
        """
        Update an existing participant
        """
        body = request.json
        participant = models.participant.query.filter_by(kf_id=kf_id).one_or_none()
        if not participant:
            return self._not_found(kf_id)

        participant.external_id = body.get('external_id')
        db.session.commit()

        return kf_response(participant, 201, 'participant updated')
```

**Comment by baileyckelly** [comment]
Linking to the Person rename issue. Should rename the entity before doing further work on it.

**Comment by znatty22** [comment]
This is OBE since #65 rewrites the Participant resource classes
