### ISSUE TITLE
History for entities

### ISSUE THREAD

**Issue by allisonheath** [kids-first/kf-api-dataservice#58]
For each entity type we'll want to capture a history of updates. Exact implementation TBD as we should lay out some of the key use cases first. 

Some builtin concepts that might help with the TBD are trigger functionality to provide similar features to postgres' old time travel feature: https://www.postgresql.org/docs/current/static/contrib-spi.html or temporal tables extensions: https://github.com/arkhipov/temporal_tables

Should use care, as time travel was originally removed because of storage and performance: https://www.postgresql.org/docs/6.3/static/c0503.htm

**Comment by dankolbman** [comment]
This warrants a lot of investigation before we jump into any implementation.

How will this work for entities outside our postgres model?
Do all entities need to be tracked historically?
Do entities modifications need to be tracked for every modification?
Perhaps only for every 'release'? (yet to be defined)
What are the user access requirements?

**Comment by allisonheath** [comment]
Also for some concepts, ERAV: https://wq.io/1.0/docs/erav

**Comment by dankolbman** [comment]
Going to close as too broad for now. The new event logging should be helpful if we ever need to generate a view of the data in a past point in time.
