### ISSUE TITLE
Update enum values for "DATA_TYPE_ENUM" and "WORKFLOW_TYPE_ENUM"

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-api-dataservice#651]
we need to update the enum values for "DATA_TYPE_ENUM" and "WORKFLOW_TYPE_ENUM" according to [kf_pipeline_outputs.csv](https://github.com/d3b-center/bixops-dataset-process/blob/master/docs/pipeline_outputs/kf_pipeline_outputs.csv)

**Comment by HuangXiaoyan0106** [comment]
Have updated it. 
https://github.com/d3b-center/bixops-dataset-process/blob/master/docs/pipeline_outputs/kf_pipeline_outputs.csv

**Comment by yuankunzhu** [comment]
should we close this ticket since the PR is merged? @znatty22
