### ISSUE TITLE
Add Investigator to the data model

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-api-dataservice#83]
Per AOC feedback of the portal mockups: 
"When they do a query can they?
They want to know who the investigators are
They also want to do a query based on an investigator"

This will require us to add investigator to the data model.

**Comment by allisonheath** [comment]
For the purposes of the MVP, we can track some basic investigator information in the data service. 

However, after the MVP this information should come from the Kids First profiles that people fill out. The idea is that investigators should have a profile and then we can associate the profile ID so as they make changes to their information (e.g. they change institutions) that is done by the user, not by our internal team. This would also allow them to share additional information, if they choose to do so.

**Comment by baileyckelly** [comment]
This entity needs discussion. We were discussing whether or not this should be in Study or be broken out separately.
